# Generated by Django 5.0.1 on 2024-02-20 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(help_text='Введите место проведения мероприятия', max_length=50, verbose_name='Место проведения мероприятия')),
                ('max_participant', models.IntegerField(blank=True, help_text='Введите колличество мест', null=True, verbose_name='Колличество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Введите название тега', max_length=25, verbose_name='Имя тега')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите название чата', max_length=50, null=True, verbose_name='Название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания мероприятия')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=50, verbose_name='Название мероприятия')),
                ('body', models.TextField(blank=True, help_text='Введите информацию о мероприятит', max_length=1000, null=True, verbose_name='Информация о мероприятии')),
                ('seats', models.IntegerField(default=1, null=True, verbose_name='Колличество свободных мест на мероприятии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания мероприятия')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения мероприятия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.OneToOneField(blank=True, help_text='Выберите чат для мероприятия', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.chat', verbose_name='Чат мероприятия')),
                ('tags', models.ManyToManyField(blank=True, help_text='Выберите теги для мероприятия', related_name='meetings_list', to='meetings.tags', verbose_name='Теги мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(help_text='Укажите вашу дату рождения', verbose_name='Дата рождения')),
                ('info', models.TextField(blank=True, help_text='Введите информацию о вас', max_length=500, null=True, verbose_name='Информация о вас')),
                ('telegram', models.CharField(blank=True, help_text='Напишите свой Telegtam', max_length=50, null=True, verbose_name='Telegtam')),
                ('chats', models.ManyToManyField(blank=True, help_text='Выберете чаты', related_name='profile', to='meetings.chat', verbose_name='Ваши чаты')),
                ('meetings', models.ManyToManyField(blank=True, help_text='Выберете мероприятия, которые хотите поситить', related_name='meetings', to='meetings.meeting', verbose_name='Мероприятия')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Выберите интересующие теги', to='meetings.tags', verbose_name='Ваши теги')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Введите сообщение', max_length=200, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Введите дату проведения мероприятия', verbose_name='Дата проведения мероприятия')),
                ('start_time', models.TimeField(help_text='Введите время начала мероприятия', verbose_name='Время начала мероприятия')),
                ('end_time', models.TimeField(help_text='Введите время окончания мероприятия', verbose_name='Время окончания мероприятия')),
                ('place', models.ForeignKey(help_text='Выберите место проведения мероприятия', on_delete=django.db.models.deletion.CASCADE, to='meetings.place', verbose_name='Место проведения мероприятия')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='timetable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.timetable'),
        ),
    ]
