# Generated by Django 5.0.1 on 2024-02-20 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название голосования', max_length=50, null=True, verbose_name='Название голосования')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название поля', max_length=50, verbose_name='Название поля')),
                ('users', models.ManyToManyField(related_name='fields', to=settings.AUTH_USER_MODEL, verbose_name='Список выбравших это поле')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='voting',
            field=models.ForeignKey(blank=True, help_text='Добавьте голосование', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.voting', verbose_name='Голосования'),
        ),
    ]
