# Generated by Django 5.0.1 on 2024-02-20 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_voting_field_meeting_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='voting',
        ),
        migrations.AddField(
            model_name='voting',
            name='voting',
            field=models.ForeignKey(blank=True, help_text='Добавьте голосование', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='Голосования'),
        ),
    ]
