# Generated by Django 5.0.1 on 2024-02-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_rename_voting_voting_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='vote',
            field=models.ForeignKey(blank=True, help_text='Выберите голосование', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='meetings.voting', verbose_name='Голосование'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='meeting',
            field=models.ForeignKey(blank=True, help_text='Выберите мероприятие', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='meetings.meeting', verbose_name='Мероприятие'),
        ),
    ]
