# Generated by Django 5.0.1 on 2024-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_timetable_author_alter_field_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='count_votes',
            field=models.IntegerField(default=0, help_text='Введите количество голосов', verbose_name='Количество голосов'),
        ),
    ]
